#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Script to take screenshots with grim, slurp (in Wayland)

iDIR="$HOME/.config/hypr/mako/icons"

# time=`date +%Y%m%d_%Hh%Mm%Ss`
time=`date +%F_%T`
# dir="`xdg-user-dir PICTURES`/Screenshots"
dir=~/Downloads/screenshots
file="screenshot_${time}.png"

# notify and view screenshot
# notify_cmd_shot="notify-send -h string:x-canonical-private-synchronous:sys-notify-shot -u low -i ${iDIR}/picture.png"
# notify_view () {
	# notify-send "Copied to clipboard."
	# paplay /usr/share/sounds/freedesktop/stereo/screen-capture.oga &>/dev/null &
	# viewnior ${dir}/"$file"
	# if [[ -e "$dir/$file" ]]; then
	# 	${notify_cmd_shot} "Screenshot Saved."
	# else
	# 	${notify_cmd_shot} "Screenshot Deleted."
	# fi
# }

# countdown
countdown () {
	for sec in `seq $1 -1 1`; do
		notify-send -h string:x-canonical-private-synchronous:sys-notify-count -t 1000 -i "$iDIR"/timer.png "Taking shot in : $sec"
		sleep 1
	done
}

# take shots
shotnow () {
	cd ${dir} && sleep 0.5 && grim - | tee "$file" | wl-copy
	notify_view
}

shot5 () {
	countdown '5'
	sleep 1 && cd ${dir} && grim - | tee "$file" | wl-copy
	notify_view
}

shot10 () {
	countdown '10'
	sleep 1 && cd ${dir} && grim - | tee "$file" | wl-copy
	notify_view
}

shotwin () {
	(cd ${dir} && hyprctl -j activewindow | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | grim -g - $file \
	&& notify-send -t 1000 "Screenshot saved as $file" \
	&& swappy -f $file)
}

shotarea () {
	(cd ${dir} && grim -g "$(slurp -b 20262CCC -c B4A1DBff -s B4A1DB0D -w 2 && sleep 0.3)" $file \
	&& notify-send "Screenshot saved as $file" \
	&& swappy -f $file)
}

if [[ ! -d "$dir" ]]; then
	mkdir -p "$dir"
fi

if [[ "$1" == "--now" ]]; then
	shotnow
elif [[ "$1" == "--in5" ]]; then
	shot5
elif [[ "$1" == "--in10" ]]; then
	shot10
elif [[ "$1" == "--win" ]]; then
	shotwin
elif [[ "$1" == "--area" ]]; then
	shotarea
else
	echo -e "Available Options : --now --in5 --in10 --win --area"
fi

exit 0
